### ISSUE TITLE
 使用2个qq号分别登录，其中一个可以正常收发，另一个只能发却收不到？

### ISSUE THREAD

**Issue by Stic-ker** [milkice233/efb-qq-slave#10]
向目标qq发送一条消息，coolq的图灵机器人也能正常反应，就是efb没反应，tg上收不到消息
但是用tg发送消息是可以的

**Comment by milkice233** [comment]
两个QQ号是分别用两个酷Q进程登录的吗

**Comment by Stic-ker** [comment]
不是，是先使用第一个qq登录发现可以正常使用，然后ctrl+c中断docker，并重新打开coolq登录第二个qq发现使用不正常。然后再重启酷q登录第一个qq，发现还是可以正常使用，没有使用两个酷q进程，efb也没有报错

**Comment by milkice233** [comment]
两个QQ号对应的 CoolQ-HTTP 插件配置可能不同

**Comment by Stic-ker** [comment]
多谢了，确实是这样
~/coolq/app/io.github.richardchien.coolqhttpapi/config下有QQ1.ini 却没有QQ2.ini，这可能是导致qq2使用不正常的原因。重新创建qq2.ini可能会解决问题，但是我rm *.* 并重启coolq使自动生成qq2.ini，这样就可以用了XD
反正我也只用一个qq，打算先凑活着233治标不治本
