### ISSUE TITLE
如果名字包括特殊字符, 将显示Unsupported characters

### ISSUE THREAD

**Issue by blue-bird1** [milkice233/efb-qq-slave#13]
如果群名片有奇怪字符, 会导致发送信息变成`Unsupported characters`

~~调查是哪个字符中~~

是`┍ ⃢👁︵ ` 真的是tg的不支持..

**Comment by milkice233** [comment]
这个…后续可以考虑转换一下（

**Comment by H1W0XXX** [comment]
优⃢━⃢秀
这个字符串显示不出来
![image](https://user-images.githubusercontent.com/56431380/174490660-49412cae-1557-4766-b7f6-75eb78036866.png)

**Comment by milkice233** [comment]
感觉这个 issue 应该交由 ETM 处理
