### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by blue-bird1** [milkice233/efb-qq-slave#14]
自用的时候 写了docker-compose文件 `https://github.com/Earth-Online/efb-qq-docker` 可以添加到readme docker安装

**Comment by milkice233** [comment]
非常感谢😃
之前一直有 dockerize 的计划但是没空 非常感谢 抽空会展示在 README 上

**Comment by milkice233** [comment]
README 中
> 打开 ip:9001 登陆novnc后完成coolq登陆操作
这句写错了 应该是 9801 端口

**Comment by blue-bird1** [comment]
readme已改正, 仓库名我改成efb-qq-coolq-docker了

**Comment by milkice233** [comment]
非常感谢 已更新 README
https://github.com/milkice233/efb-qq-slave/commit/9272db1b7d1f9a90924475b97317573db540c083
