### ISSUE TITLE
efb-telegram-master的update_info功能支持

### ISSUE THREAD

**Issue by mshuang2516** [milkice233/efb-qq-slave#20]
master有一个很好用的功能 
链接聊天到群组后，输入/update_info后就可以修改改群组名称为从端获取到的name 以及 profile picture到群组信息中。十分方便。
而qq-slave会报：
Error occurred while update chat information. 
'ETMChat' object has no attribute 'channel_id'
的错误，求大佬支持。谢谢

**Comment by milkice233** [comment]
已加入 To-do List

**Comment by milkice233** [comment]
https://github.com/milkice233/efb-qq-slave/commit/c9af116942951cc5182aa04454cbb2991ff73075
请更新 efb-qq-slave 之后试下

**Comment by mshuang2516** [comment]
抱歉我没想到支持得这么快！
谢谢作者支持，我刚刚更新到最新测试后已经可以了。
