### ISSUE TITLE
set_restart接口 在coolq api4.9 被移除了 导致relogin失效

### ISSUE THREAD

**Issue by blue-bird1** [milkice233/efb-qq-slave#25]
https://github.com/richardchien/coolq-http-api/issues/176

**Comment by milkice233** [comment]
察觉到了此问题，目前在和 Richard Chien 讨论是否恢复该 API

**Comment by milkice233** [comment]
https://github.com/milkice233/efb-qq-slave/commit/f24858d074e92fd2384482a4de7cf61780a137bf
