### ISSUE TITLE
Unable to connect to CoolQ Client

### ISSUE THREAD

**Issue by kevinzhang1234** [milkice233/efb-qq-slave#26]
![image](https://user-images.githubusercontent.com/46987925/55941286-817e2380-5c74-11e9-96a6-30b2f9d8116f.png)
我使用两台机器，其中一台运行酷Q，另外一台运行efb

**Comment by blue-bird1** [comment]
https://github.com/richardchien/coolq-http-api/issues/177 如此问题讨论 等待上游修复（作者说今晚发版本）后更新docker容器
