### ISSUE TITLE
依赖版本号检查导致启动失败

### ISSUE THREAD

**Issue by AkazaDorian** [milkice233/efb-qq-slave#28]
错误信息是
`pkg_resources.ContextualVersionConflict: (h11 0.9.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('h11~=0.8.1'), {'wsproto'})`
应该是本地的版本号比较高

**Comment by milkice233** [comment]
这个...是哪个依赖出的问题

**Comment by manyang901** [comment]
请尽快release移除了aiocqhttp依赖后的版本。
此h11依赖问题较为严重，建议尽快修复，谢谢！

**Comment by milkice233** [comment]
> 请尽快release移除了aiocqhttp依赖后的版本。
> 此h11依赖问题较为严重，建议尽快修复，谢谢！

十分抱歉，已推送2.0.0a6，请测试一下是否还有问题

**Comment by AkazaDorian** [comment]
> 
> 
> > 请尽快 release 移除了 aiocqhttp 依赖后的版本。
> > 此 h11 依赖问题较为严重，建议尽快修复，谢谢！
> 
> 十分抱歉，已推送 2.0.0a6，请测试一下是否还有问题

测试过已经修复了，感谢
