### ISSUE TITLE
使用EH Forwarder Bot，尝试多开后，失败。

### ISSUE THREAD

**Issue by eatneko** [milkice233/efb-qq-slave#29]
在进程中可以看见两个CQP.exe，但打开voNVC，voNVC就彻底卡死了。没办法多开

**Comment by milkice233** [comment]
noVNC卡死是指…？

**Comment by AkazaDorian** [comment]
noVNC 的端口改了吗

**Comment by eatneko** [comment]
noVNC卡死是指，成功登陆VNC后，无法操作酷Q。
可能是我配置不当，请问该怎么配置，可以双开酷Q。。。

**Comment by milkice233** [comment]
无法操作酷Q？
是否有日志

**Comment by eatneko** [comment]
CoolQ Alert:
Failed to obtain friend remark name...最近，coolq更新了，出现了这个问题，所以是插件内容不匹配了吗

**Comment by AkazaDorian** [comment]
@eatneko 更新 slave，还有发现 bug 不要发在无关的 issue 里
