### ISSUE TITLE
Failed to obtain friend remark name

### ISSUE THREAD

**Issue by AkazaDorian** [milkice233/efb-qq-slave#30]
![](https://i.imgur.com/X9PWiSH.png) 

如图，今天更新了一下出现的这个，同时会有群消息有些人只显示空白昵称的情况（非好友）

**Comment by milkice233** [comment]
已经发现此问题，和上游CQHTTP作者沟通的情况来看是获取好友列表的 API 爆炸，正在寻找替代接口

**Comment by milkice233** [comment]
已紧急更换 API 请先手动从 enh-group_broadcast 分支上更新一下 EQS 然后再启动 EFB 看下效果
`pip3 install git+https://github.com/milkice233/efb-qq-slave.git@enh-group_broadcast`
匆忙修改 可能还有些bug 麻烦帮忙测试下

**Comment by AkazaDorian** [comment]
@milkice233 试用了一晚上，没有发现一样的问题，不过不清楚有没有别的问题

**Comment by milkice233** [comment]
> @milkice233 试用了一晚上，没有发现一样的问题，不过不清楚有没有别的问题

那我先推送到主分支了 否则根本没法用
