### ISSUE TITLE
无法获取好友列表，只有群组被展示以及无法获取朋友评论名称

### ISSUE THREAD

**Issue by oneplus1plus5** [milkice233/efb-qq-slave#32]
![image](https://user-images.githubusercontent.com/46640871/61197749-19265e80-a709-11e9-905c-2d2399a2fa3d.png)
![image](https://user-images.githubusercontent.com/46640871/61197876-ae295780-a709-11e9-9f89-53dfefd347c2.png)

懂得不多，谷歌了好几天也没有找到解决办法，见谅

**Comment by oneplus1plus5** [comment]
我已经试过了上一个关闭问题里提出的方法，但是还是不能解决

**Comment by milkice233** [comment]
> 我已经试过了上一个关闭问题里提出的方法，但是还是不能解决

最新版按理说应该已经修复了 请问你是否有执行过 `pip3 install --upgrade efb-qq-slave`

**Comment by oneplus1plus5** [comment]
![image](https://user-images.githubusercontent.com/46640871/61273902-2f9dea00-a7dd-11e9-8cc8-01fb898bc19a.png)
 已经执行过了，还是一样的问题，而且我的也拉取不到联系人，只能拉取群组消息，我再研究一下吧，重新搞一下，看是不是哪里配置的有问题。麻烦你了

**Comment by milkice233** [comment]
> ![image](https://user-images.githubusercontent.com/46640871/61273902-2f9dea00-a7dd-11e9-8cc8-01fb898bc19a.png)
> 已经执行过了，还是一样的问题，而且我的也拉取不到联系人，只能拉取群组消息，我再研究一下吧，重新搞一下，看是不是哪里配置的有问题。麻烦你了

你用的是docker版的，可能容器里的EQS已经非常旧了，和主机的EQS没关系

**Comment by oneplus1plus5** [comment]
好的，谢谢大佬了，实在是麻烦你了
