### ISSUE TITLE
启动ehforwarderbot报错

### ISSUE THREAD

**Issue by gaxdel** [milkice233/efb-qq-slave#42]
ehforwarderbot.__main__ (__main__.init; __main__.py:85)
     Initializing slave milkice.qq...
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 269, in main
    init(conf)
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/__init__.py", line 43, in __init__
    self.load_config()
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/__init__.py", line 69, in load_config
    self.config: Dict[str, Any] = yaml.load(f)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml", line 2, column 5

**Comment by milkice233** [comment]
配置文件格式有误哦，看下吧

**Comment by gaxdel** [comment]
> 
> 
> 配置文件格式有误哦，看下吧

改好了，多谢。tg bot能发送信息，但是收不到信息，不知道是什么原因。

**Comment by gaxdel** [comment]
> 
> 
> > 配置文件格式有误哦，看下吧
> 
> 改好了，多谢。tg bot能发送信息，但是收不到信息，不知道是什么原因。

看到前面有同样问题的issue了，先去试下

**Comment by gaxdel** [comment]
@milkice233 跟 #33 一样，服务器上酷Q日志里面显示接收到了qq消息，但是tg bot收不到qq消息，尝试把/root/.ehforwarderbot/profiles/default/blueset.telegram中的tgdata.db删除，bot就无法运行了，重启ehforwarderbot会自动生成tgdata.db文件。

**Comment by milkice233** [comment]
诶…好奇怪啊…暂时没什么想法…

**Comment by milkice233** [comment]
有人反馈是 CQHTTP 依赖版本过低导致
可尝试通过 pip3 install --upgrade cqhttp 来更新
EQS 2.0.0b1 已强制要求依赖版本，更新到此版本之后应该就无此问题

**Comment by gaxdel** [comment]
> 
> 
> 有人反馈是 CQHTTP 依赖版本过低导致
> 可尝试通过 pip3 install --upgrade cqhttp 来更新
> EQS 2.0.0b1 已强制要求依赖版本，更新到此版本之后应该就无此问题

更新了，使用的是EQS最新版，你博客里新老方法都试了，tg还是收不到qq发来的消息，通过ehforwarderbot --verbose 命令看不到QQ发消息的log，有什么日志需要提供的么？

**Comment by gaxdel** [comment]
> 
> 
> > 有人反馈是 CQHTTP 依赖版本过低导致
> > 可尝试通过 pip3 install --upgrade cqhttp 来更新
> > EQS 2.0.0b1 已强制要求依赖版本，更新到此版本之后应该就无此问题
> 
> 更新了，使用的是EQS最新版，你博客里新老方法都试了，tg还是收不到qq发的消息，通过ehforwarderbot --verbose 命令看不到QQ发消息的log，有什么日志需要提供的么？

emmm之前不知道是哪里操作出了问题，不断xjb试，后面换了老方法，更新cqhttp，tg能收到信息了了。tg无法查看酷q登录状态和重新登录：EFB Telegram 主端遇到错误 'function' object has no attribute 'name'。

**Comment by milkice233** [comment]
还有更具体的日志吗
这个似乎是在执行自定义命令的时候（/0_login）触发的？

**Comment by gaxdel** [comment]
> 
> 
> 还有更具体的日志吗
> 这个似乎是在执行自定义命令的时候（/0_login）触发的？

执行/h_0_login 和 /h_0_relogin命令的错误日志：
`[ERROR]: efb_telegram_master (__init__.error; __init__.py:529)
    Unhandled telegram bot error!
Update {'update_id': 414360530, 'message': {'message_id': 1003, 'date': 1580634945, 'chat': {'id': 202283157, 'type': 'private', 'username': 'gaxddd', 'first_name': 'z', 'last_name': 'zxz'}, 'text': '/h_0_login', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 20283157, 'first_name': 'z', 'is_bot': False, 'last_name': 'zxz', 'username': 'gaxddd', 'language_code': 'zh-hans'}}, '_effective_user': {'id': 202283157, 'first_name': 'z', 'is_bot': False, 'last_name': 'zxz', 'username': 'gaxddd', 'language_code': 'zh-hans'}, '_effective_chat': {'id': 202283157, 'type': 'private', 'username': 'gaddd', 'first_name': 'z', 'last_name': 'zxz'}, '_effective_message': {'message_id': 1003, 'date': 1580634945, 'chat': {'id': 202283157, 'type': 'private', 'username': 'gaxddd', 'first_name': 'z', 'last_name': 'zxz'}, 'text': '/h_0_login', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 202283157, 'first_name': 'z', 'is_bot': False, 'last_name': 'zxz', 'username': 'gaxddd', 'language_code': 'zh-hans'}}} caused error 'function' object has no attribute 'name'. Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/__init__.py", line 459, in error
    raise error
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/commands.py", line 207, in extra_usage
    html.escape(command.name),
AttributeError: 'function' object has no attribute 'name'`
执行/0_login命令 显示coolq状态检查完成。

**Comment by milkice233** [comment]
> > 还有更具体的日志吗
> > 这个似乎是在执行自定义命令的时候（/0_login）触发的？
> 
> 执行/h_0_login 和 /h_0_relogin命令的错误日志：
> `[ERROR]: efb_telegram_master (__init__.error; __init__.py:529) Unhandled telegram bot error! 'function' object has no attribute 'name'. Exception Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/__init__.py", line 459, in error raise error File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 372, in process_update handler.handle_update(update, self, check, context) File "/usr/local/lib/python3.6/dist-packages/telegram/ext/handler.py", line 117, in handle_update return self.callback(update, context) File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/commands.py", line 207, in extra_usage html.escape(command.name), AttributeError: 'function' object has no attribute 'name'`
> 执行/0_login命令 显示coolq状态检查完成。

按理说不会出现这样的问题……旧版 ETM 才会出现的问题
