### ISSUE TITLE
收到的 gif 不会动

### ISSUE THREAD

**Issue by AkazaRenn** [milkice233/efb-qq-slave#44]
对方发出来的图：
![](https://i.imgur.com/2iG2NcI.gif)
我收到的：
![](https://i.imgur.com/GpTsNf3.jpg)

**Comment by milkice233** [comment]
之前有人提交了一个pr修复了这个问题，我随后会发布release

**Comment by milkice233** [comment]
https://github.com/milkice233/efb-qq-slave/pull/38
