### ISSUE TITLE
在使用/link时能否将群聊设置在在前面展示

### ISSUE THREAD

**Issue by Sduby22** [milkice233/efb-qq-slave#45]
由于好友过多，每次需要翻好久才能翻到群聊，有没有办法把群聊放在好友前面或者输入/link后先分组显示呢

**Comment by milkice233** [comment]
为什么不直接 /link 后面跟上群组名呢
比如 /link xxx

**Comment by Sduby22** [comment]
哇多谢，都不知道可以这样用

milkice <notifications@github.com> 于 2019年11月8日周五 09:25写道：
