### ISSUE TITLE
Cannot send message to groups

### ISSUE THREAD

**Issue by TTTPOB** [milkice233/efb-qq-slave#46]
I cannot send messages to groups whether in unlinked chat with the bot, or the linked chat.

But I can see the messges from the groups, and can view/send messages with friends.

**Comment by milkice233** [comment]
Please provide more information, such as your configs, logs, etc.

**Comment by TTTPOB** [comment]
I've just opened the delog log of cqhttp, when I send messages to friends, I get this.
![image](https://user-images.githubusercontent.com/19909103/68947317-1be8ab80-07f0-11ea-97fd-07140a8cf759.png)

**Comment by TTTPOB** [comment]
So there are two questions instead of one:
1. Messages sent to telegram group A (linked with QQ group B) will not be sent to B
2. Messages sent to B via efb will not appear in qq

**Comment by milkice233** [comment]
It seems to be the issue of CoolQ part since EFB can reach CoolQ and there's no connection problem.
Have you tried restarting CoolQ? Sometimes CoolQ needs to be updated to comply with the current protocol of QQ.
And also please have a check on the privacy settings of your bot.

**Comment by TTTPOB** [comment]
Extremely sorry for that... In fact I have read about the privacy setting part of the manual, but somehow I did not change it ( I thought I had changed it 

so, I think the problem is on tencent/coolq side.

Thank you for explanation
