### ISSUE TITLE
can we get rid of this ad?

### ISSUE THREAD

**Issue by llldar** [milkice233/efb-qq-slave#5]
![screen shot 2018-09-25 at 3 14 42 pm](https://user-images.githubusercontent.com/9290574/45998586-e3f74400-c0d5-11e8-997d-0a4a3fd761d9.jpg)
so embarrassing...

**Comment by milkice233** [comment]
Login to your noVNC console and disable unnecessary plugins in CoolQ.

**Comment by llldar** [comment]
problem solved, thx.
