### ISSUE TITLE
建议合并分支

### ISSUE THREAD

**Issue by NavePnow** [milkice233/efb-qq-slave#50]
前几天更新了ehforwarderbot，发现结构变化太大了，efb-qq-slave直接崩了，我下载了最新的那个分支，替换了site-package里面对应的文件夹才行。估计蛮多小伙伴都会更新ehforwarderbot，所以还是建议作者合并一下分支，或者版本管理一下？谢了

**Comment by milkice233** [comment]
EFB_2.0.0b26 分支因为还在测试阶段，暂时没考虑合并...
当然这两天测试下来应该已经可以发到主分支了

**Comment by milkice233** [comment]
已合并
