### ISSUE TITLE
"Failed to update friend remark name"

### ISSUE THREAD

**Issue by AkazaRenn** [milkice233/efb-qq-slave#52]
更新到 2.0.0b1 之后出现的，会不停刷

**Comment by milkice233** [comment]
建议重新登录酷Q端，应该是 Cookie 过期
因为现在只能从 show.qq.com 拿好友分组信息

**Comment by AkazaRenn** [comment]
> 建议重新登录酷 Q 端，应该是 Cookie 过期
> 因为现在只能从 show.qq.com 拿好友分组信息

确实是这样，已解决，感谢
