### ISSUE TITLE
酷q上报成功，但是tg收不到消息，如何查看日志解决

### ISSUE THREAD

**Issue by lmikoto** [milkice233/efb-qq-slave#53]
![image](https://user-images.githubusercontent.com/46601514/73535665-18fc6f00-445f-11ea-950d-5d6e14311cfe.png)

**Comment by milkice233** [comment]
这个日志只是 酷Q 端成功接收到 EQS 发来的请求 表明 EQS -> 酷Q端方向是通的，但是不代表 酷Q->EQS 方向是通的
看下 EFB 日志吧

**Comment by lmikoto** [comment]
日志没发现什么，重启发现莫名其妙好了。
