### ISSUE TITLE
Telegram Group 消息link到 QQ Group 的时候添加发送人姓名

### ISSUE THREAD

**Issue by WangJi** [milkice233/efb-qq-slave#54]
你好，我已经成功`link`了`Telegram Group`和`QQ Group`之间的相互转发通信。    
#### 问题
`telegram`的消息从`group`转发到`qq group`的时候，没有发送人的姓名，反之则有。    
如图：     
![image](https://user-images.githubusercontent.com/5742670/74063062-a6752b80-4a2a-11ea-9d6d-0e5278aa5ab9.png)    
#### 期望
在`QQ Group`的转发消息前面能加上 ***WangJi:*** 的前缀，标明**发送人**。    

是否漏掉了一些配置项？烦请指点一下。

**Comment by milkice233** [comment]
也就是说，你想实现，在 TG 上自己回复自己的消息时，在QQ上所呈现的引用消息中带上 自己在TG上的用户名是么

**Comment by WangJi** [comment]
对的，我是想让QQ上呈现的消息，在无论何时，都**带有TG的用户名**。     

-------------------

我的使用场景是想让这个bot当做`tg group`和`qq group`的所有消息的相互转发。   
不过看了一下`ETM`的使用场景，好像还不满足我这个需求，我再想想看别的办法。

**Comment by WangJi** [comment]
`telegram id `不在 `admins`配置项中的`tg`用户，即便在`group`里，也无法从`tg group`中发送消息到`qq group`

**Comment by milkice233** [comment]
是的，如果你的目标是TG和QQ群互联，建议参考这个项目https://github.com/jqqqqqqqqqq/UnifiedMessageRelay
本项目是用于个人消息转发

**Comment by WangJi** [comment]
ok，谢谢大佬。
