### ISSUE TITLE
 efb qq 无法接收私人发的文件

### ISSUE THREAD

**Issue by junyixu** [milkice233/efb-qq-slave#58]
我无法知道个人是否有发文件给我，不知道是不是自己的配置错误

**Comment by junyixu** [comment]
一些好友直接发文件，什么话都不说，我便不知道他发了文件

**Comment by milkice233** [comment]
是这样的
原因是 酷Q 无法接受到个人发来的文件（是的 连提示都没有），所以这边 EQS 也无能为力

**Comment by junyixu** [comment]
等酷Q支持之前暂时先在 qq 签名中写 “ 请用 https://send.firefox.com 私发文件” 好了

**Comment by milkice233** [comment]
这边和 CQHTTP 作者排查了下，酷Q的确会收到一个空消息，正在问 CQHTTP 作者能否把这个空消息一同上报

**Comment by XYenon** [comment]
可以试一下用 [go-cqhttp](https://docs.go-cqhttp.org)配合 https://github.com/XYenon/efb-qq-plugin-go-cqhttp 插件，已经支持了接受好友发送的离线文件
