### ISSUE TITLE
mirai 启动ehforwarderbot报错

### ISSUE THREAD

**Issue by Backonemore** [milkice233/efb-qq-slave#64]
![Snipaste_2020-09-10_11-34-53](https://user-images.githubusercontent.com/64834906/92678974-c28ed180-f359-11ea-8c90-3e57f6be70a2.png)
报错信息为
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml", line 2, column 9
见上图

![Snipaste_2020-09-10_11-31-40](https://user-images.githubusercontent.com/64834906/92678774-498f7a00-f359-11ea-8798-385d328967a8.png)
在启动miriai之后，出现两条[ERROR]信息为
[ERROR] [CQHTTPMirai] Exception in ReportService
[ERROR] [CQHTTPMirai] java.net.ConnectException: Failed to connect to
/127.0.0.1:8000
见上图

**Comment by Backonemore** [comment]
我的”/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml“配置文件内容如下图
![Snipaste_2020-09-10_11-49-43](https://user-images.githubusercontent.com/64834906/92679760-e81cda80-f35b-11ea-9cd7-4500117f0946.png)

**Comment by Backonemore** [comment]
我在第2行的末尾添加空格，还有不添加空格，这两种都尝试了，依然是这个报错

**Comment by milkice233** [comment]
是这样的

先启动 mirai, mirai 会报错没关系, 然后启动 EQS, 再回到 mirai 重新启动就好了
现阶段只能这样……过渡方案

**Comment by Backonemore** [comment]
谢谢解答，我按照您提供的方法试了一下。

但是是我启动EQS(使用ehforwarderbot命令)的时候，依然产生报错
yaml.scanner.ScannerError: mapping values are not allowed here
in "/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml", line 2, column 9
导致无法启动EQS

**Comment by milkice233** [comment]
> 谢谢解答，我按照您提供的方法试了一下。
> 
> 但是是我启动EQS(使用ehforwarderbot命令)的时候，依然产生报错
> yaml.scanner.ScannerError: mapping values are not allowed here
> in "/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml", line 2, column 9
> 导致无法启动EQS

配置文件第二行缩进不对，顶格写

**Comment by Backonemore** [comment]
感谢您的帮助，按照您说的修改配置文件之后，成功启动EQS！

（题外话，您的博客好像无法访问了）

**Comment by Backonemore** [comment]
![image](https://user-images.githubusercontent.com/64834906/92688477-fb39a580-f36f-11ea-9c24-4ff5a228e4c5.png)


还有就是，图中的路径我这边是plugins/settings.yml

**Comment by milkice233** [comment]
> ![image](https://user-images.githubusercontent.com/64834906/92688477-fb39a580-f36f-11ea-9c24-4ff5a228e4c5.png)
> 
> 还有就是，图中的路径我这边是plugins/settings.yml

谢谢纠正，我等会儿去改

**Comment by Backonemore** [comment]
您好，我刚刚换了一台机器部署，在启动EQS的时候(已经启动了mirai)，遇到了报错
Exception: We're unable to communicate with CoolQ Client.
Please check the connection and credentials provided.
Unable to connect to CoolQ Client!Error Message:
HTTPConnectionPool(host='127.0.0.1', port=5700): Max retries exceeded with url: /get_status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5526137588>: Failed to establish a new connection: [Errno 111] Connection refused',))
如下图

![image](https://user-images.githubusercontent.com/64834906/92693783-ab131100-f378-11ea-9586-9f809fdac697.png)

**Comment by milkice233** [comment]
> 您好，我刚刚换了一台机器部署，在启动EQS的时候(已经启动了mirai)，遇到了报错
> Exception: We're unable to communicate with CoolQ Client.
> Please check the connection and credentials provided.
> Unable to connect to CoolQ Client!Error Message:
> HTTPConnectionPool(host='127.0.0.1', port=5700): Max retries exceeded with url: /get_status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5526137588>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 如下图
> 
> ![image](https://user-images.githubusercontent.com/64834906/92693783-ab131100-f378-11ea-9586-9f809fdac697.png)

Mirai 配置有误，贴下 Mirai 配置

**Comment by Backonemore** [comment]
我发现问题了，我在新机器上部署的时候，mirai的配置文件路径是“plugins/setting.yml"，我之前直接编辑的是“plugins/settings.yml"。

现在改过来了，已经成功启动EQS，感谢帮助！

**Comment by milkice233** [comment]
ok
