### ISSUE TITLE
Mirai客户端,在启动ehforwarderbot时报错

### ISSUE THREAD

**Issue by Rewrite0** [milkice233/efb-qq-slave#74]
- 设备: 树莓派4b
- 系统: Debian-Pi-Aarch64
启动efb后的输出如下:
![image](https://user-images.githubusercontent.com/49576640/109458516-eaa0f700-7a97-11eb-953f-17c301c08ac7.png)
一步步搞到最后,启动给我搞个这个,差点把我心态搞炸,但是我实在是看不懂了...

另外中途在装efb-qq-plugin-mirai时,装完有个依赖问题:  
> aiohttp 3.7.3 requires chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.  
于是我把chardet给降到3.0.4了,不知道有没有关系,但是还是提一下吧.  
同时为了装efb-qq-plugin-mirai,重新编译安装了python3.8,毕竟树莓派的python版本没有3.8...  
求大佬帮忙.

**Comment by 0honus0** [comment]
Mirai的好像有bug？
建议用IOTbot的

**Comment by Rewrite0** [comment]
@0honus0 已经在准备换IOT的了,不过还是想问问...

**Comment by 0honus0** [comment]
> @0honus0 已经在准备换IOT的了,不过还是想问问...

不清楚这个问题，之前配置是没问题的，看着像缺什么东西或者配置错误。

**Comment by Rewrite0** [comment]
> > @0honus0 已经在准备换IOT的了,不过还是想问问...
> 
> 不清楚这个问题，之前配置是没问题的，看着像缺什么东西或者配置错误。

搞不太懂,先放这吧..

**Comment by milkice233** [comment]
aiohttp 版本过于先进
试试 ``pip3 install aiohttp==3.7.4``

**Comment by Rewrite0** [comment]
> aiohttp 版本过于先进
> 试试 `pip3 install aiohttp==3.7.4`

现在是这样:   
![image](https://user-images.githubusercontent.com/49576640/109470748-cb5f9500-7aaa-11eb-8fcb-8254ea837658.png)
应该把这个解决就行了:   
> ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.

**Comment by milkice233** [comment]
> > aiohttp 版本过于先进
> > 试试 `pip3 install aiohttp==3.7.4`
> 
> 现在是这样:
> ![image](https://user-images.githubusercontent.com/49576640/109470748-cb5f9500-7aaa-11eb-8fcb-8254ea837658.png)
> 应该把这个解决就行了:
> 
> > ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.

EFB 的 requirement 里要求 libwebp
如果你用的是 debian 系列的发行版的话试试 `sudo apt install libwebp6`

**Comment by Rewrite0** [comment]
> > > aiohttp 版本过于先进
> > > 试试 `pip3 install aiohttp==3.7.4`
> > 
> > 
> > 现在是这样:
> > ![image](https://user-images.githubusercontent.com/49576640/109470748-cb5f9500-7aaa-11eb-8fcb-8254ea837658.png)
> > 应该把这个解决就行了:
> > > ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.
> 
> EFB 的 requirement 里要求 libwebp
> 如果你用的是 debian 系列的发行版的话试试 `sudo apt install libwebp6`

装了没用..

**Comment by milkice233** [comment]
> > > > aiohttp 版本过于先进
> > > > 试试 `pip3 install aiohttp==3.7.4`
> > > 
> > > 
> > > 现在是这样:
> > > ![image](https://user-images.githubusercontent.com/49576640/109470748-cb5f9500-7aaa-11eb-8fcb-8254ea837658.png)
> > > 应该把这个解决就行了:
> > > > ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.
> > 
> > 
> > EFB 的 requirement 里要求 libwebp
> > 如果你用的是 debian 系列的发行版的话试试 `sudo apt install libwebp6`
> 
> 装了没用..

抱歉是 `sudo apt install libwebp-dev`
装完之后重装下 Pillow `pip3 install --no-deps --force-reinstall Pillow`

**Comment by Rewrite0** [comment]
> > > > > aiohttp 版本过于先进
> > > > > 试试 `pip3 install aiohttp==3.7.4`
> > > > 
> > > > 
> > > > 现在是这样:
> > > > ![image](https://user-images.githubusercontent.com/49576640/109470748-cb5f9500-7aaa-11eb-8fcb-8254ea837658.png)
> > > > 应该把这个解决就行了:
> > > > > ehforwarderbot.exceptions.EFBException: WebP support of Pillow is required.
> > > 
> > > 
> > > EFB 的 requirement 里要求 libwebp
> > > 如果你用的是 debian 系列的发行版的话试试 `sudo apt install libwebp6`
> > 
> > 
> > 装了没用..
> 
> 抱歉是 `sudo apt install libwebp-dev`
> 装完之后重装下 Pillow `pip3 install --no-deps --force-reinstall Pillow`

好家伙,成了,感谢大佬的耐心帮助!!!

**Comment by Rewrite0** [comment]
有了一个新问题,目前发消息是正常的,但是接收不了任何消息.

**Comment by Rewrite0** [comment]
换成IOTBot无此问题.

**Comment by milkice233** [comment]
> 有了一个新问题,目前发消息是正常的,但是接收不了任何消息.

发现了，可能是我最后一次 commit 出问题了，在排查

**Comment by Rewrite0** [comment]
> > 有了一个新问题,目前发消息是正常的,但是接收不了任何消息.
> 
> 发现了，可能是我最后一次 commit 出问题了，在排查

好的,再次感谢大佬今天的帮助

**Comment by milkice233** [comment]
> > > 有了一个新问题,目前发消息是正常的,但是接收不了任何消息.
> > 
> > 
> > 发现了，可能是我最后一次 commit 出问题了，在排查
> 
> 好的,再次感谢大佬今天的帮助

是上游 Pydantic 前两天发布的 1.8 版本引入的 Bug
试试 `pip3 install pydantic==1.7.3` 后再启动 EFB

**Comment by Rewrite0** [comment]
> > > > 有了一个新问题,目前发消息是正常的,但是接收不了任何消息.
> > > 
> > > 
> > > 发现了，可能是我最后一次 commit 出问题了，在排查
> > 
> > 
> > 好的,再次感谢大佬今天的帮助
> 
> 是上游 Pydantic 前两天发布的 1.8 版本引入的 Bug
> 试试 `pip3 install pydantic==1.7.3` 后再启动 EFB

测试可行
