### ISSUE TITLE
启动后不定期Telegram会收不到消息

### ISSUE THREAD

**Issue by a-kami** [milkice233/efb-qq-slave#75]
RT,大概每隔几分钟就会出现一次，tg bot不会发消息，但可以发送消息到QQ，再过几分钟就会恢复正常，一直这样循环
mirai模式，不是onebot。mirai-console里一切正常
EFB只有这一条
![image](https://user-images.githubusercontent.com/57009175/110136335-8751f480-7e0a-11eb-8c7d-9cfd1fdb3651.png)

**Comment by milkice233** [comment]
> RT,大概每隔几分钟就会出现一次，tg bot不会发消息，但可以发送消息到QQ，再过几分钟就会恢复正常，一直这样循环
> mirai模式，不是onebot。mirai-console里一切正常
> EFB只有这一条
> ![image](https://user-images.githubusercontent.com/57009175/110136335-8751f480-7e0a-11eb-8c7d-9cfd1fdb3651.png)

用 `ehforwarderbot -v` 启动， 然后在收不到消息的时候看下日志？
能不能稳定复现呢

**Comment by milkice233** [comment]
观察了下我这边也会出现类似的情况……还是比较头疼的，因为依赖的库是异步 IO 单线程，的确有卡线程的可能
