### ISSUE TITLE
Mirai-api-http模式下的备注问题

### ISSUE THREAD

**Issue by shejialuo** [milkice233/efb-qq-slave#79]
今天在服务器将efb-qq-slave的客户端更新为了mirai-api-http，仍然是无法得到好友的备注。看了一下mirai-api-http的官方文档，有一个[GET] /friendList?sessionKey=YourSessionKey方法能够获取nickname字段，请问一下能够增加一下这个功能吗？以及现在重构的版本是否能够实现该功能，有时间我也可以尝试贡献一下。最后很感谢作者重构的版本支持了mirai-api-http。

**Comment by milkice233** [comment]
实际上已经实现了这个功能，不能显示好友备注是因为上游 mirai-api-http 之前还不支持返回用户备注，这两天应该会推新版

**Comment by milkice233** [comment]
https://github.com/project-mirai/mirai-api-http/issues/279
https://github.com/project-mirai/mirai-api-http/releases/tag/v1.10.0
实际上已经修了+发布了
mirai-api-http 更新到 1.10.0 试试

**Comment by shejialuo** [comment]
嗯嗯，感谢作者的解答！
