### ISSUE TITLE
运行时出现Specified client not found

### ISSUE THREAD

**Issue by pixia1234** [milkice233/efb-qq-slave#84]
运行时出现Specified client not found.但是从端已经配置完成，opqbot已经做好

**Comment by milkice233** [comment]
跟 #83 的问题应该是一样的
整个项目还在测试，请从 Github 上拉源代码
`pip3 install git+https://github.com/milkice233/efb-qq-slave`

**Comment by milkice233** [comment]
但是这个报错可能涵盖了别的配置错误，请贴出详细错误日志

**Comment by runapp** [comment]
我用的mirai，不过大概是没什么关系的。

```
2021-06-18 01:30:32,875 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
     Initializing slave milkice.qq...
Traceback (most recent call last):
  File "/usr/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/lib/python3.6/site-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/usr/lib/python3.6/site-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
  File "/usr/lib/python3.6/site-packages/efb_qq_slave/ClientMgr.py", line 31, in __init__
    raise Exception("Specified client not found!")
Exception: Specified client not found!
```

**Comment by Yxue-1906** [comment]
> ~我用的mirai，不过大概是没什么关系的。我的`pkg_resources.iter_entry_points('ehforwarderbot.qq.plugin')`直接就是空的……~
> 
> 看花了，原来还得额外装一个python包，而且还是要3.8以上的
> 
> ```
> 2021-06-18 01:30:32,875 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
>      Initializing slave milkice.qq...
> Traceback (most recent call last):
>   File "/usr/bin/ehforwarderbot", line 8, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 335, in main
>     init(conf)
>   File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 135, in init
>     coordinator.add_channel(cls(instance_id=instance_id))
>   File "/usr/lib/python3.6/site-packages/efb_qq_slave/__init__.py", line 44, in __init__
>     self.init_client_manager()
>   File "/usr/lib/python3.6/site-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
>     self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
>   File "/usr/lib/python3.6/site-packages/efb_qq_slave/ClientMgr.py", line 31, in __init__
>     raise Exception("Specified client not found!")
> Exception: Specified client not found!
> ```

你的问题解决了吗? 我的报错日志和你相同

**Comment by jiesou** [comment]
挖，我遇到好多次这个问题了，给以后遇到这个问题的人：

其实就是没有装某些东西，检查一下
```
pip3 install ehforwarderbot
pip3 install efb-telegram-master
pip3 install efb-qq-slave

pip3 install efb-qq-plugin-go-cqhttp
或
pip3 install efb-qq-plugin-mirai
或
pip3 install efb-qq-plugin-iot
```

尤其是那个客户端还需要装对应的插件，很容易漏掉
