### ISSUE TITLE
[help wanted] 转发群消息的时候只能转发我自己发出的消息...

### ISSUE THREAD

**Issue by JYInMyHeart** [milkice233/efb-qq-slave#85]
使用`mirai`客户端的时候，转发tg群消息只能转发我自己的消息，其他群友的消息都视而不见...

版本信息
- git最新版efb-qq-slave
- release 最新版mirai

**Comment by milkice233** [comment]
EFB 作为一个个人 IM 的替代品本就如此设计的，如果你需要 QQ 和 TG 两边的群组互联你可能需要这个项目 https://github.com/JQ-Networks/UnifiedMessageRelay

**Comment by JYInMyHeart** [comment]
> EFB 作为一个个人 IM 的替代品本就如此设计的，如果你需要 QQ 和 TG 两边的群组互联你可能需要这个项目 https://github.com/JQ-Networks/UnifiedMessageRelay

原来是这样  只要不是我的操作出了问题就好。 顺便非常感谢您的贡献，很棒哦😊
