### ISSUE TITLE
关于新增功能的咨询及代码贡献问题 | mirai /update_info无法更新群组头像

### ISSUE THREAD

**Issue by shejialuo** [milkice233/efb-qq-slave#87]
首先仍然是感谢作者的贡献，在这儿有几个不情之请：

1. 能否可以支持文件的上传以及文件的接收。
    我在上游看了一些文档，[POST] /uploadFileAndSend，支持文件的上传。
    但是似乎没有看见文件的接收。
2. 能否可以支持语音的上传以及语音的接收。

其次是对代码贡献的一些问题：

1. 由于目前的主分支源代码，仍然有coolq，所以下手源代码较困难。
    作者能否简要地给一个开发手册。
2. 开发的一个代码风格的要求是什么？

**Comment by milkice233** [comment]
我假设你指的都是 mirai
前两个问题
1. 有段时间没看 mirai-api-http 了，有空我可能会实现一下
2. 印象里 mirai-api-http 那边之前仅支持群组语音，所以当时没实现，我过会儿去看下

代码贡献问题
1. 因为是重构过的，客户端核心代码都挪到单独的 repository 里去了，主分支的源码里的 CoolQ 代码暂时保留着是为了防止不经意间依赖了相关代码后导致程序运行错误
2. 代码风格按照 PEP 的要求就行，没有那么严苛，提交PR后如果需要修改我会单独再交个 commit

**Comment by shejialuo** [comment]
十分不好意思，那天发issue的时候忘记指明对象了。

我今天去看了一下 python-mirai-core, Bot类目前是没有文件上传的方法的。

目前 mirai 似乎已经能支持文件、语音和视频的上传和下载。（但是不清楚是否支持私聊）相关Issue:

https://github.com/mamoe/mirai/issues/805

实际上感觉 mirai-api-http 2.0 相对于1.0的变化会比较大。

https://github.com/project-mirai/mirai-api-http/issues/215

所以个人觉得作者没必要在这个时候实现这两个功能，上游较不稳定。这个事情我没有调查清楚，
十分不好意思哈。

PS: 我今天看了一下python-mirai-core 及 efb_qq_plugin_mirai的代码，还是理解了不少。
有一个问题就是/update_info在绑定了群组的情况下执行，可以修改群组的名称为备注名，但是无法
修改群组的头像。

![image](https://user-images.githubusercontent.com/56911263/120919390-e534f780-c6eb-11eb-9f56-3f1c78c8b328.png)

实际上， python-mirai-core 存在能够获取到头像的方法：

![image](https://user-images.githubusercontent.com/56911263/120919535-b9664180-c6ec-11eb-9df3-66736c0d9239.png)

有时间，我看能否提交PR,处理一下这个问题。

**Comment by milkice233** [comment]
> PS: 我今天看了一下python-mirai-core 及 efb_qq_plugin_mirai的代码，还是理解了不少。
有一个问题就是/update_info在绑定了群组的情况下执行，可以修改群组的名称为备注名，但是无法
修改群组的头像。

请问你用的EQS用的是哪个客户端呢，我这边 efb_qq_plugin_mirai 是可以成功获取头像的

**Comment by shejialuo** [comment]
我使用的是 efb_qq_plugin_mirai。

![image](https://user-images.githubusercontent.com/56911263/120926223-9b113d80-c70e-11eb-90cf-ad066292bc5c.png)

efb-qq-slave版本为2.0.0rc1

![image](https://user-images.githubusercontent.com/56911263/120926289-da3f8e80-c70e-11eb-884d-c5a787d6bbc6.png)

efb-qq-plugin-mirai版本为

![image](https://user-images.githubusercontent.com/56911263/120926328-f80cf380-c70e-11eb-86a8-b57f05b87342.png)

操作系统信息

![image](https://user-images.githubusercontent.com/56911263/120926378-2be81900-c70f-11eb-96bd-2e84206f92a1.png)

执行/update_info操作控制台输出：(无任何输出。)

![image](https://user-images.githubusercontent.com/56911263/120926465-9600be00-c70f-11eb-8752-ac92086b4a43.png)

**Comment by milkice233** [comment]
这个我这边真的没能复现……
https://github.com/milkice233/efb-qq-plugin-mirai/blob/2cb0334c8c661b060377eb7d0cd024aa03fa8848/efb_qq_plugin_mirai/mirai.py#L265
这里已经实现了对于头像的获取，而且我这边没能复现所以真的挺奇怪……

你可以试试用 Dev 版本的 EFB + ETM + EQS 看看还有没有问题
`pip3 install git+https://github.com/milkice233/efb-qq-slave git+https://github.com/milkice233/efb-qq-plugin-mirai git+https://github.com/blueset/ehForwarderBot git+https://github.com/blueset/efb-telegram-master`

**Comment by shejialuo** [comment]
这边更新到了dev版本，仍然是 No profile picture provided from this chat。

![image](https://user-images.githubusercontent.com/56911263/120927223-ae260c80-c712-11eb-80d4-5b2fc3897828.png)

这是输出，红框部分感觉有问题。太奇怪了

**Comment by milkice233** [comment]
那就很奇怪了……我现在只能先放置……可能的猜测是下载文件失败了，然后没有报错，传给ETM的文件为空
chat id 是负值是因为 Telegram 那边的群组 chat id 好像都是负的

**Comment by milkice233** [comment]
修了 请 `pip3 install -U git+https://github.com/milkice233/efb-qq-plugin-mirai` 然后试下
