### ISSUE TITLE
efb启动失败

### ISSUE THREAD

**Issue by StephenSSR** [milkice233/efb-qq-slave#92]
Traceback (most recent call last):
      File "/usr/local/bin/ehforwarderbot", line 10, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 330, in main
        conf = config.load_config()
      File "/usr/local/lib/python3.8/site-packages/ehforwarderbot/config.py", line 47, in load_config
        raise ValueError(_("\"{}\" is not found.").format(master_channel_id))
    ValueError: "blueset.telegram" is not found.

mirai和mirai-api-http都正常启动，还是我哪里配置错了，请问该怎么解决？

**Comment by 0honus0** [comment]
配置错了，找不到blueset.telegram

**Comment by StephenSSR** [comment]
![捕获](https://user-images.githubusercontent.com/45059048/124680444-03636280-def9-11eb-9f58-52d14fe730e0.PNG)

我是有这个·文件的，但是不知道哪里出了问题

**Comment by 0honus0** [comment]
看不出来，建议贴一下配置

**Comment by StephenSSR** [comment]
deafult下 config.yaml配置

    master_channel: blueset.telegram
    slave_channels:
    - milkice.qq

blueset.telegram下配置

    token: "******************************************"   #从tg @BotFather处获得的token
    admins:
    - **********                                   #设置管理员
    flags:
      send_image_as_file: true
      #将所有图像消息作为文件发送,以防止主动报文的图像压缩.需要更多的流量,可以关闭,改为false
      default_media_prompt: text
      #图片/视频/文件消息没有标题时的占位符文本.

milkice.qq下配置

    Client: mirai
    mirai:
      qq: ************           # 这里换成登录的 QQ 号
      host: "127.0.0.1"       # Mirai HTTP API 监听地址，一般是 127.0.0.1
      port: 8080              # Mirai HTTP API 监听端口，一般是 8080
      authKey: "28nrq0vnj02y" # 这里填入在配置 Mirai API HTTP 时生成的 authKey

net.mamoe.mirai-api-http下配置

    cors:
      - '*'
    host: 127.0.0.1
    port: 8080
    authKey: 28nrq0vnj02y        # 这里随机生成一个字符串
    cacheSize: 4096
    enableWebsocket: true  # 确保 Websocket 已经启用
    report:
      enable: true         # 确保这里是 true 用来启用消息上报
      groupMessage:
        report: true
      friendMessage:
        report: true
      tempMessage:
        report: true
      eventMessage:
        report: true
      destinations: []
      extraHeaders: {}

    heartbeat:
      enable: false
      delay: 1000
      period: 15000
      destinations: []
      extraBody: {}
      extraHeaders: {}

请问还需要什么吗

**Comment by 0honus0** [comment]
好像是ehforwarderbot telegram主端没有安装好？
